# ---------- BUILD STAGE ----------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy full solution
COPY . .

# Restore dependencies
RUN dotnet restore

# Publish API project
RUN dotnet publish medicineAPI/medicineAPI.csproj -c Release -o /app/out


# ---------- RUNTIME STAGE ----------
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

# Copy published files
COPY --from=build /app/out .

# Expose port
EXPOSE 10000

# Run API
ENTRYPOINT ["dotnet", "medicineAPI.dll"]